#!/bin/bash

# ═══════════════════════════════════════════════════
#  help.sh — Full documentation for gitflow-cli
#  Triggered by: gitflow --help or gitflow -h
# ═══════════════════════════════════════════════════

show_help() {
  echo ""
  echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════════╗${RESET}"
  echo -e "${BOLD}${CYAN}║         gitflow — Smart Git Tool             ║${RESET}"
  echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════╝${RESET}"
  echo ""
  echo -e "${BOLD}COMMANDS:${RESET}"
  echo -e "  ${GREEN}gitflow${RESET}              Push your code to GitHub"
  echo -e "                       If no repo found, offers to init or clone"
  echo -e "  ${GREEN}gitflow --pull${RESET}       Pull latest code from GitHub"
  echo -e "  ${GREEN}gitflow --sync${RESET}       Same as --pull"
  echo -e "  ${GREEN}gitflow --checkout${RESET}   Switch branch, create branch, search"
  echo -e "  ${GREEN}gitflow --continue${RESET}   Finish push after fixing conflicts manually"
  echo -e "  ${GREEN}gitflow --clone${RESET}      Clone a GitHub repo to your laptop"
  echo -e "  ${GREEN}gitflow --log${RESET}        View your push history"
  echo -e "  ${GREEN}gitflow --help${RESET}       Show this documentation"
  echo ""
  echo -e "${BOLD}${YELLOW}── WHEN NO GIT REPO FOUND ──────────────────────${RESET}"
  echo -e "  Running ${CYAN}gitflow${RESET} in a folder with no git repo will ask:"
  echo ""
  echo -e "  ${DIM}[1] Initialize new repo${RESET}"
  echo -e "  ${DIM}    → Fresh git repo, set remote URL, first push${RESET}"
  echo -e "  ${DIM}[2] Clone existing repo from GitHub${RESET}"
  echo -e "  ${DIM}    → Download a project from GitHub to your laptop${RESET}"
  echo ""
  echo -e "${BOLD}${YELLOW}── PUSHING (gitflow) ───────────────────────────${RESET}"
  echo -e "  ${BOLD}Step 1 — File staging:${RESET}"
  echo -e "  Shows all changed files with a number."
  echo -e "  • Press ${GREEN}Enter${RESET}       → stage ALL files"
  echo -e "  • Type ${GREEN}1${RESET} or ${GREEN}1 3${RESET}   → stage specific files by number"
  echo ""
  echo -e "  ${BOLD}Step 2 — Commit message:${RESET}"
  echo -e "  Shows last 3 commits and suggests a message."
  echo -e "  • Press ${GREEN}Enter${RESET}       → accept suggestion"
  echo -e "  • Type your own   → use custom message"
  echo ""
  echo -e "  ${BOLD}Step 3 — Branch:${RESET}"
  echo -e "  Lists all branches as a numbered menu."
  echo -e "  • Press ${GREEN}Enter${RESET}       → use current branch"
  echo -e "  • Type ${GREEN}number${RESET}       → pick from list"
  echo -e "  • Type ${GREEN}f/login${RESET}      → creates feature/login"
  echo -e "  • Type ${GREEN}b/login${RESET}      → creates bugfix/login"
  echo -e "  • Type ${GREEN}h/login${RESET}      → creates hotfix/login"
  echo -e "  • Type ${GREEN}r/v2${RESET}         → creates release/v2"
  echo -e "  • Type ${GREEN}any-name${RESET}     → creates that branch"
  echo ""
  echo -e "  ${BOLD}Step 4 — Safety:${RESET}"
  echo -e "  Shows a full summary before pushing."
  echo -e "  Asks ${GREEN}y/n${RESET} confirmation. Warns if pushing to main."
  echo ""
  echo -e "${BOLD}${YELLOW}── CHECKOUT (gitflow --checkout) ───────────────${RESET}"
  echo -e "  Smart branch switcher with pagination and search."
  echo ""
  echo -e "  ${BOLD}How to use:${RESET}"
  echo -e "  • Type ${GREEN}number${RESET}       → switch to that branch"
  echo -e "  • Type ${GREEN}b${RESET}            → create a new branch"
  echo -e "  • Type ${GREEN}n${RESET}            → next page (10 per page)"
  echo -e "  • Type ${GREEN}p${RESET}            → previous page"
  echo -e "  • Type ${GREEN}s${RESET}            → search branch by name"
  echo -e "  • Type ${GREEN}c${RESET}            → clear search, show all"
  echo -e "  • Type ${GREEN}branch-name${RESET}  → checkout directly by name"
  echo -e "  • Type ${GREEN}q${RESET}            → cancel"
  echo ""
  echo -e "  After switching, asks to pull latest with Merge or Rebase."
  echo ""
  echo -e "  ${BOLD}Direct checkout:${RESET}"
  echo -e "  ${GREEN}gitflow --checkout dev${RESET}  → jumps straight to dev"
  echo ""
  echo -e "  ${BOLD}Create branch shortcuts:${RESET}"
  echo -e "  ${GREEN}f/name${RESET}  → feature/name"
  echo -e "  ${GREEN}b/name${RESET}  → bugfix/name"
  echo -e "  ${GREEN}h/name${RESET}  → hotfix/name"
  echo -e "  ${GREEN}r/name${RESET}  → release/name"
  echo ""
  echo -e "${BOLD}${YELLOW}── PULLING (gitflow --pull) ─────────────────────${RESET}"
  echo -e "  Fetches latest code from GitHub."
  echo -e "  Offers two sync methods:"
  echo ""
  echo -e "  ${BOLD}[1] Merge${RESET} ${GREEN}← recommended${RESET}"
  echo -e "  Grabs new code and combines it with yours."
  echo -e "  Think of it like: two rivers joining into one."
  echo -e "  ${GREEN}Safe for teams. Nothing gets lost.${RESET}"
  echo ""
  echo -e "  ${BOLD}[2] Rebase${RESET} ${DIM}← experienced users only${RESET}"
  echo -e "  Moves YOUR commits on top of the new code."
  echo -e "  Think of it like: cutting your work and"
  echo -e "  re-pasting it after the latest changes."
  echo -e "  ${RED}⚠ Avoid on shared/public branches.${RESET}"
  echo ""
  echo -e "  ${BOLD}If conflicts are found:${RESET}"
  echo -e "  [1] Take remote version  → overwrite with GitHub version"
  echo -e "  [2] Keep my version      → ignore their changes"
  echo -e "  [3] Fix manually         → fix in editor, run gitflow --continue"
  echo -e "  [4] Abort                → go back to before the pull"
  echo ""
  echo -e "${BOLD}${YELLOW}── CLONING (gitflow --clone) ────────────────────${RESET}"
  echo -e "  Downloads any GitHub repo to your laptop."
  echo -e "  Supports both SSH and HTTPS URLs."
  echo -e "  ${DIM}SSH   : git@github.com:username/repo.git${RESET}"
  echo -e "  ${DIM}HTTPS : https://github.com/username/repo.git${RESET}"
  echo ""
  echo -e "${BOLD}${YELLOW}── AFTER PUSH ──────────────────────────────────${RESET}"
  echo -e "  Shows commit hash and GitHub branch URL."
  echo -e "  Logs every push to ${CYAN}~/.gitflow_history${RESET}"
  echo -e "  View history: ${GREEN}gitflow --log${RESET}"
  echo ""
  echo -e "${DIM}════════════════════════════════════════════════${RESET}"
  echo ""
}